Repository open-webrtc-toolkit/owt-client-javascript, pull requests merged in 2020-12, with the labels that each got.

#384 Add WebTransport support.
  docs/design/webtransport.md
  docs/mdfiles/changelog.md
  package.json
  scripts/Gruntfile.js
  src/samples/conference/README.md
  src/samples/conference/package-lock.json
  src/samples/conference/public/quic.html
  src/samples/conference/public/scripts/quic.js
  src/sdk/base/export.js
  src/sdk/base/publication.js
  src/sdk/base/stream.js
  src/sdk/base/transport.js
  src/sdk/conference/channel.js
  src/sdk/conference/client.js
  src/sdk/conference/quicconnection.js
  src/sdk/conference/subscription.js
Labels: comp:conference, enhancement

#442 Update changelog.
  docs/mdfiles/changelog.md
Labels: enhancement

#429 Avoid abnormal sdp state when publication/subscription failed
  src/sdk/conference/channel.js
Labels: bug

#450 Creating QUIC connection after checking QuicTransport.
  src/sdk/conference/client.js
Labels: bug

#451 Set bundle policy to max-bundle on Chrome only.
  src/sdk/conference/channel.js
Labels: bug, comp:conference, firefox
